version: "3"
services:
  test:
    container_name: test
    environment:
      SECRET_KEY: test
      FLASK_ENV: test
      FLASK_APP: microblog.py
    build:
      context: .
      dockerfile: docker/Dockerfile_test

  prod:
    container_name: prod
    environment:
      SECRET_KEY: production
      DATABASE_URL: mysql+pymysql://microblog:pass@{{ groups['database'][0] }}/microblog
      FLASK_APP: microblog.py
      FLASK_ENV: production
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    links:
      - mysql:dbserver
    ports:
      - "5000:5000"

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql-data:/var/lib/mysql

  prod_no_db:
    container_name: prod_no_db
    environment:
      SECRET_KEY: prod2
      DATABASE_URL: mysql+pymysql://microblog:pass@0.0.0.0:3306/microblog
      FLASK_APP: microblog.py
      FLASK_ENV: production
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    ports:
      - "5000:5000"

  start:
    container_name: start
    image: moau17/microblog_prod:latest
    restart: always
    ports:
      - "5000:5000"
