---
############## Node_exporter ##############
- name: Create node_exporter user group
  group: name="node_exporter"
  become: true

- name: Create node_exporter user
  user:
    name: "node_exporter"
    group: "node_exporter"
    system: yes
    shell: "/sbin/nologin"
    comment: "node_exporter nologin User"
    createhome: "no"
    state: present

- name: Install prometheus node exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_build }}.tar.gz"
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus node exporter file to bin
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_build }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "node_exporter"
    group: "node_exporter"
    remote_src: yes
    mode: 0755

- name: Delete node exporter tmp folder
  file:
    path: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_build }}"
    state: absent

- name: Setup node_exporter system service
  template:
    src: "services/node_exporter_service.j2"
    dest: /etc/systemd/system/node_exporter.service

- name: Reload daemon
  command: sudo systemctl daemon-reload

- name: Start node_exporter
  command: sudo systemctl start node_exporter

- name: Curl to see node_exporter metrics
  uri:
    url: http://localhost:9100/metrics
    method: GET
    status_code: 200
  ignore_errors: yes

############## Prometheus ##############
- name: Create prometheus user group
  group: name="prometheus"
  become: true

- name: Create prometheus user
  user:
    name: "prometheus"
    group: "prometheus"
    system: yes
    shell: "/sbin/nologin"
    comment: "prometheus nologin User"
    createhome: "no"
    state: present

- name: Creates data directory for prometheus
  file:
    path: "/data/prometheus/"
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: 0755

- name: Create directory for prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: 0755

- name: Download prometheus file
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_build }}.tar.gz
    dest: /
    remote_src: yes

- name: Extract downloaded prometheus file
  unarchive:
    src: /prometheus-{{ prometheus_version }}.{{ prometheus_build }}.tar.gz
    dest: /etc/prometheus
    remote_src: yes

- name: Change in the file of prometheus.yml
  template:
    src: "templates/prometheus_conf.j2"
    dest: /etc/prometheus/prometheus-{{ prometheus_version }}.{{ prometheus_build }}/prometheus.yml

- name: Start prometheus
  shell: "/usr/bin/sudo /etc/prometheus/prometheus-{{ prometheus_version }}.{{ prometheus_build }}/prometheus --config.file=/etc/prometheus/prometheus-{{ prometheus_version }}.{{ prometheus_build }}/prometheus.yml --web.enable-lifecycle  --storage.tsdb.path=/data/prometheus --storage.tsdb.retention.time=2d &"
  args:
    executable: "/bin/bash"

- name: Curl to see if prometheus is accessible
  uri:
    url: http://localhost:9090/prometheus/graph
    method: GET
    status_code: 200
  ignore_errors: yes
